services:
  reverse-proxy:
    image: traefik:v3.3.0
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "8080:8080" # Traefik panel
      - "443:443" # HTTPS port
    volumes:
      # So that Traefik can listen to Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt

  db:
    image: postgres:17.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4.0.5-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"  # RabbitMQ main port
      - "15672:15672"  # RabbitMQ management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  sensepro:
    image: ghcr.io/moreorover/sensepro-admin-panel-development:${VERSION:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sensepro.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.sensepro.entrypoints=websecure"
      - "traefik.http.routers.sensepro.tls.certresolver=myresolver"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@$db:5432/${POSTGRES_DB}
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${${RABBITMQ_PASSWORD}}@rabbitmq:5672
    deploy:
      update_config:
        order: start-first
      mode: replicated
      replicas: 3
    depends_on:
      - db
      - rabbitmq

volumes:
  letsencrypt:
  rabbitmq_data:
  postgres_data:
    driver: local
