services:
  db:
    image: postgres:17.2
    container_name: sense_pro_pg
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "7070:8080"
    depends_on:
      - db

  rabbitmq:
    image: rabbitmq:4.0.5-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ main port
      - "15672:15672"  # RabbitMQ management UI port
    env_file:
      - ./.env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  sensepro:
    build:
      context: ../../
      dockerfile: docker/local/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
      - rabbitmq

volumes:
  rabbitmq_data:
  postgres_data:
    driver: local
