name: Build and Push Docker Images on Release

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [development, production]

    environment: ${{ matrix.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "${GITHUB_TOKEN}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
#          platforms: linux/amd64,linux/arm64
          build-args: |
            ENV=${{ matrix.environment }}
            SECRET=${{ secrets.MY_DEV_SECRET }}
            TAG=${{ github.ref_name }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/sensepro-admin-panel-${{ matrix.environment }}:latest
            ghcr.io/${{ github.repository_owner }}/sensepro-admin-panel-${{ matrix.environment }}:${{ github.ref_name }}
